name: CI-CD
on:
   push:
     branches: ["main"]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0
      - name: Build image docker
        uses: docker/build-push-action@v5.0.0
        with: 
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            nandofpc/aulagitactions:v1
            nandofpc/aulagitactions:latest
