name: CI-CD
on:
   push:
     branches: ["main"]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0

      - name: Autenticação Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKERUB_USR}}
          password: ${{secrets.DOCKERHUB_PWD}}
      - name: Build image docker
        uses: docker/build-push-action@v5.0.0
        with: 
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            nandofpc/aulagitactions:v1
            nandofpc/aulagitactions:latest
