name: CI-CD
on:
   push:
     branches: ["main"]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0

      - name: Autenticação Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKERHUB_USR}}
          password: ${{secrets.DOCKERHUB_PWD}}
      - name: Build image docker
        uses: docker/build-push-action@v5.0.0
        with: 
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            nandofpc/aulagitactions:v${{github.run_number}}
            nandofpc/aulagitactions:latest
  CD:
     runs-on: ubuntu-latest
     needs: [CI]
     steps:
     - uses: actions/checkout@v4.0.0
     - name: Azure Kubernetes set context
       uses: Azure/aks-set-context@v3
       with:
         method: kubeconfig
         kubeconfig: ${{secrets.K8S_CONFIG}}
     - name: Deploy to kubernetes cluster
       uses: Azure/k8s-deploy@v4
       with:
         images: nandofpc/aulagitactions:v${{github.run_number}}
         manifests: |
           k8s/deployment.yaml
